import {CLASS_ACCESS_KEY} from './classes-api.js?phase=2b17';
const node=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
const button=(text,fn)=>{const b=node('button',text);b.type='button';b.onclick=fn;return b;};
const localDate=value=>{if(!value)return '';const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,19);};
export function legacyScheduleDrafts(data,identity){
  return data.sessions.filter(s=>s.schoolId===identity.schoolId).map(session=>{
    const assessment=data.assessments.find(a=>a.assessmentId===session.assessmentId&&a.schoolId===identity.schoolId);
    return {session,assessment};
  });
}
export function showSchedules({container,identity,client,classesClient,initialClasses,tests,legacyDrafts,accessStorage}){
  const root=node('section');container.append(root);const key=CLASS_ACCESS_KEY+':'+identity.schoolId+':'+identity.teacherId;
  const zone=Intl.DateTimeFormat().resolvedOptions().timeZone;
  let records=[],classes=initialClasses,ready=false,busy=false,message='',failed=false,editing=null;
  const blank=()=>({testName:'',testId:tests[0]?.testId||'',classIds:[],period:false,open:'',close:''});let draft=blank();
  const credential=()=>{try{return accessStorage.getItem(key)||'';}catch{return '';}};
  async function run(label,fn){if(busy)return;busy=true;message=label;failed=false;draw();try{await fn();}catch(e){failed=true;message=e.message+(label.startsWith('Loading')||label.startsWith('Refreshing')?' Shared data could not be loaded. Local drafts and pending saves were retained.':' Save is not confirmed. Keep this browser data and retry; the server may already have received the operation.');}finally{busy=false;if(root.isConnected)draw();}}
  const merge=s=>{records=[...records.filter(r=>r.scheduleId!==s.scheduleId),s];};
  async function refresh(){ready=false;const freshClasses=await classesClient.list(),fresh=await client.list();classes=freshClasses;records=fresh;ready=true;message='Schedules loaded from Google Sheets.';}
  async function save(action,input){const saved=await client.mutate(action,input);merge(saved);ready=true;message='Saved to Google Sheets (server confirmed).';return saved;}
  function timeText(record){if(!record.openAt)return 'No planned availability period';try{const format=new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short',timeZone:record.timeZone});return format.format(new Date(record.openAt))+' – '+format.format(new Date(record.closeAt))+' · '+record.timeZone;}catch{return record.openAt+' – '+record.closeAt+' · '+record.timeZone;}}
  function draw(){
    root.replaceChildren(node('h1','Schedule Test'),node('p','Shared planning only. These settings do not publish a student test or control student access.'));
    const status=node('p',message||'Connect to load shared schedules.');status.className=failed?'error':'muted';status.setAttribute('role',failed?'alert':'status');root.append(status);
    const connection=node('form');connection.className='card';const label=node('label','Classes access key');label.className='field';const input=node('input');input.type='password';input.autocomplete='off';input.required=true;input.value=credential();input.disabled=busy;label.append(input);const connect=node('button',ready?'Refresh Schedules':'Connect Schedules');connect.type='submit';connect.disabled=busy;connection.append(label,connect,node('small','Uses the same private school key as Classes.'));
    connection.onsubmit=e=>{e.preventDefault();run('Loading shared schedules…',async()=>{accessStorage.setItem(key,input.value.trim());await refresh();});};root.append(connection);
    let pending;try{pending=client.pending();}catch(e){root.append(node('p',e.message));ready=false;}
    if(pending){const panel=node('section');panel.className='card';panel.append(node('h2','Unconfirmed Schedule save'),node('p',pending.action+': '+(pending.testName||pending.scheduleId)),node('small','Schedule ID: '+pending.scheduleId),node('p','The operation is retained locally. Retry uses the same Schedule ID and operation ID.'));
      const retry=button('Retry saving',()=>run('Retrying the same Schedule save…',async()=>{const saved=await client.retry();merge(saved);editing=null;draft=blank();try{await refresh();message='Saved to Google Sheets (server confirmed).';}catch(e){ready=false;failed=true;message='Schedule save confirmed, but list refresh failed: '+e.message;}}));retry.disabled=busy||!credential();panel.append(retry);
      if(pending.rejectedWithoutWrite){const discard=button('Discard rejected change',()=>run('Refreshing Schedules…',async()=>{client.discardRejected();await refresh();}));discard.disabled=busy;panel.append(node('p','The server rejected this request without a new write. Discard removes only the local pending retry; any existing Sheets row is retained. Refresh and edit again.'),discard);}root.append(panel);
    }
    const form=node('form');form.className='card';form.dataset.scheduleEditor='true';form.append(node('h2',editing?'Edit Schedule':'Create Schedule'));
    const disabled=busy||!ready||!!pending;
    const nameLabel=node('label','Test name');nameLabel.className='field';const name=node('input');name.required=true;name.maxLength=120;name.value=draft.testName;name.disabled=disabled;name.oninput=()=>draft.testName=name.value;nameLabel.append(name);form.append(nameLabel);
    const setLabel=node('label','Question set');setLabel.className='field';const set=node('select');set.disabled=disabled;for(const t of tests){const option=node('option',t.testName);option.value=t.testId;set.append(option);}set.value=draft.testId;set.onchange=()=>draft.testId=set.value;setLabel.append(set);form.append(setLabel);
    const targets=node('fieldset');targets.append(node('legend','Target Classes'));
    for(const c of classes.filter(c=>c.status==='active'||(editing&&editing.classIds.includes(c.classId)))){const l=node('label');l.className='checkbox-row';const check=node('input');check.type='checkbox';check.value=c.classId;check.checked=draft.classIds.includes(c.classId);check.disabled=disabled||(c.status!=='active'&&!check.checked);check.onchange=()=>{draft.classIds=check.checked?[...new Set([...draft.classIds,c.classId])]:draft.classIds.filter(id=>id!==c.classId);if(c.status!=='active')check.disabled=true;};l.append(check,document.createTextNode(' '+c.className+(c.status==='archived'?' (archived; existing target)':'')),node('small','Class ID: '+c.classId));targets.append(l);}
    if(!classes.some(c=>c.status==='active'))targets.append(node('p',ready?'Add or Restore an active Class in Classes.':'Connect to load target Classes.'));form.append(targets);
    const availability=node('fieldset');availability.append(node('legend','Planned availability (does not restrict students)'));
    const dates=node('div');dates.hidden=!draft.period;
    const dateInputs=[];for(const [title,k]of [['Open date/time','open'],['Close date/time','close']]){const l=node('label',title);l.className='field';const i=node('input');i.type='datetime-local';i.step='1';i.value=draft[k];i.disabled=disabled||!draft.period;i.required=draft.period;i.oninput=()=>draft[k]=i.value;l.append(i);dates.append(l);dateInputs.push(i);}
    for(const [value,text]of [[false,'No planned period'],[true,'Set planned period']]){const l=node('label');l.className='checkbox-row';const radio=node('input');radio.type='radio';radio.name='period';radio.checked=draft.period===value;radio.disabled=disabled;radio.onchange=()=>{draft.period=value;dates.hidden=!value;dateInputs.forEach(i=>{i.disabled=disabled||!value;i.required=value;});};l.append(radio,document.createTextNode(' '+text));availability.append(l);}availability.append(dates,node('small','Enter times in '+zone+'. Saved times include UTC timestamps and the time zone.'));form.append(availability);
    const submit=node('button',editing?'Save Changes':'Create Schedule');submit.type='submit';submit.disabled=disabled;form.append(submit);
    if(editing){const cancel=button('Cancel editing',()=>{editing=null;draft=blank();draw();});cancel.disabled=busy;form.append(cancel,node('small','Schedule ID: '+editing.scheduleId));}
    form.onsubmit=e=>{e.preventDefault();draft={...draft,testName:name.value,testId:set.value,classIds:[...targets.querySelectorAll('input:checked')].map(i=>i.value),open:dateInputs[0].value,close:dateInputs[1].value};run('Saving Schedule…',async()=>{if(!draft.classIds.length)throw Error('Select at least one active Class.');if(draft.period&&(!Number.isFinite(Date.parse(draft.open))||!Number.isFinite(Date.parse(draft.close))||Date.parse(draft.close)<=Date.parse(draft.open)))throw Error('Select a valid opening and closing time.');const data={testName:draft.testName.trim(),testId:draft.testId,classIds:draft.classIds,openAt:draft.period?new Date(draft.open).toISOString():null,closeAt:draft.period?new Date(draft.close).toISOString():null,timeZone:zone};await save(editing?'update':'create',{...data,...(editing?{scheduleId:editing.scheduleId,expectedUpdatedAt:editing.updatedAt}:{})});editing=null;draft=blank();});};root.append(form,node('h2','Shared Schedules'));
    if(ready&&!records.length)root.append(node('p','No shared schedules yet.'));
    for(const r of [...records].sort((a,b)=>b.createdAt.localeCompare(a.createdAt))){const card=node('section');card.className='card';card.append(node('h2',r.testName),node('p','Status: '+(r.status==='disabled'?'Disabled':'Enabled (planning only)')),node('p','Question set: '+(tests.find(t=>t.testId===r.testId)?.testName||r.testId)),node('p',r.classIds.map(id=>{const c=classes.find(c=>c.classId===id);return (c?.className||'Unknown Class')+' ['+id.slice(0,8)+']'+(c?.status==='archived'?' (archived)':'');}).join(', ')),node('p',timeText(r)),node('small','Schedule ID: '+r.scheduleId),node('small','Updated: '+new Date(r.updatedAt).toLocaleString()));
      const controls=node('div');controls.className='row';const edit=button('Edit',()=>{editing=r;draft={testName:r.testName,testId:r.testId,classIds:[...r.classIds],period:!!r.openAt,open:localDate(r.openAt),close:localDate(r.closeAt)};draw();root.querySelector('[data-schedule-editor]')?.scrollIntoView({block:'start'});});edit.disabled=disabled;
      const toggle=button(r.status==='disabled'?'Enable Schedule':'Disable Schedule',()=>run('Saving Schedule status…',()=>save(r.status==='disabled'?'enable':'disable',{scheduleId:r.scheduleId,expectedUpdatedAt:r.updatedAt})));toggle.disabled=disabled;controls.append(edit,toggle);card.append(controls);root.append(card);
    }
    if(legacyDrafts.length){const section=node('section');section.className='card';section.append(node('h2','Local drafts from Phase 1 / 2A'),node('p','These drafts remain in this browser. Import individually after checking their Classes. Import preserves the original Session ID as the Schedule ID; no automatic duplicate registration.'));
      for(const {session:s,assessment:a}of legacyDrafts){const item=node('div');item.className='class-row';item.append(node('h3',a?.testName||'Unmatched local draft'),node('small','Original Session ID: '+s.sessionId));if(a)item.append(node('p',timeText({...s,timeZone:s.timeZone||zone})),node('p',a.targetClassIds.map(id=>(classes.find(c=>c.classId===id)?.className||'Missing Class')+' ['+id.slice(0,8)+']').join(', ')));
        if(records.some(r=>r.scheduleId===s.sessionId))item.append(node('p','Already in Google Sheets. Local draft retained.'));
        else{const migrate=button('Import this draft',()=>run('Importing local draft…',()=>save('import',{scheduleId:s.sessionId,legacyAssessmentId:a.assessmentId,createdAt:a.createdAt,testName:a.testName,testId:a.testId,classIds:a.targetClassIds,openAt:s.openAt||null,closeAt:s.closeAt||null,timeZone:s.timeZone||zone})));migrate.disabled=disabled||!a;item.append(migrate);}section.append(item);
      }root.append(section);
    }
  }
  draw();if(credential())run('Loading shared schedules…',refresh);
}
