import {TEST,validateQuestions,createAttempt,remaining,grade,validAttempt} from './core.js';
import {readingWords,readingInstruction,splitMaterialTable,readingTableWidths,choiceTextRuns} from './presentation.js?mobile-ui=10';
import {STUDENT_FIELDS,PART_NAMES} from './config.js';
import {AudioPlayer} from './audio-player.js';
import {RESULT_DELIVERY} from './result-delivery-config.js?send-v=2';
import {ensureAttemptId,resultPayload,createResultDelivery} from './result-delivery.js?durable-v=8';
import {createResultPdf,resultDate,elapsedText} from './result-pdf.js';
const audioPlayer=new AudioPlayer();
let resultPdfUrl=null,resultSaveUnsubscribe=null;
const resultDelivery=createResultDelivery({endpoint:RESULT_DELIVERY.webAppUrl,storage:{getItem:key=>localStorage.getItem(key),setItem:(key,value)=>localStorage.setItem(key,value)}});
const app=document.querySelector('#app'),meta=document.querySelector('#test-meta'),dialog=document.querySelector('#confirm-dialog');
const storageKey=`${TEST.id}:attempt:v1`;
const teacherE2EMode=location.hash==='#teacher-e2e-9-75b3cc6d0ea24a30';
let questions,attempt=null,audioManifest={},confirmAction=null,storageFailed=false;
const el=(tag,text,className)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;};
const button=(text,action,className)=>{const b=el('button',text,className);b.type='button';b.onclick=action;return b;};
function persist(){try{localStorage.setItem(storageKey,JSON.stringify(attempt));return true;}catch{if(!storageFailed){storageFailed=true;app.prepend(el('p','Progress could not be saved. Check browser storage before continuing.','error'));}return false;}}
function stopAudio(){audioPlayer.cancel();}
function showConfirm(title,message,action,label='Continue'){confirmAction=action;document.querySelector('#dialog-title').textContent=title;document.querySelector('#dialog-message').textContent=message;document.querySelector('#accept-dialog').textContent=label;dialog.showModal();}
document.querySelector('#cancel-dialog').onclick=()=>dialog.close();
document.querySelector('#accept-dialog').onclick=()=>{dialog.close();if(attempt&&!attempt.submittedAt&&remaining(attempt)===0){submit(true);return;}confirmAction?.();};
function renderParts(){const list=document.querySelector('#part-overview');list.replaceChildren();PART_NAMES.forEach((name,i)=>{const part=i+1;const status=!attempt?'Not started':attempt.submittedAt||part<attempt.section?'Completed':part===attempt.section?'Current':'Not started';const item=el('li',undefined,'part-'+status.toLowerCase().replace(' ','-'));if(status==='Current')item.setAttribute('aria-current','step');item.append(el('strong',part+': '+name),el('span',status));list.append(item);});}
function showStart(){resultSaveUnsubscribe?.();resultSaveUnsubscribe=null;meta.hidden=true;renderParts();app.replaceChildren();const card=el('section',undefined,'card start');card.append(el('div','PRACTICE TEST 01','eyebrow'),el('h1',TEST.title),el('p','Enter your details to begin. All fields are required.','muted'));const form=el('form');for(const field of STUDENT_FIELDS){const wrapper=el('label',undefined,'field'),input=el('input');input.name=field.key;input.required=field.required;input.maxLength=field.maxLength;input.autocomplete=field.autocomplete;wrapper.append(el('span',field.label),input);form.append(wrapper);}const facts=el('div',undefined,'facts');for(const [value,label]of [['50','Questions'],['60','Minutes'],['4','Parts']]){const f=el('div');f.append(el('strong',value),el('span',label));facts.append(f);}form.append(facts,el('p','You cannot return to a part after continuing. Listening questions move forward only.','muted'),el('p','Listening audio: each question can be played up to two times.','notice'));const start=el('button','Start Test','wide');start.type='submit';form.append(start);form.onsubmit=e=>{e.preventDefault();const data=new FormData(form),student=Object.fromEntries(STUDENT_FIELDS.map(f=>[f.key,String(data.get(f.key)||'').trim()]));student.rawName=String(data.get('name')||'');if(STUDENT_FIELDS.some(f=>f.required&&!student[f.key])){form.querySelectorAll('input').forEach(input=>{input.setCustomValidity(!input.required||input.value.trim()?'':'Please enter this field.');input.oninput=()=>input.setCustomValidity('');});form.reportValidity();return;}attempt=createAttempt(questions,student);if(teacherE2EMode)attempt.teacherE2E=true;ensureAttemptId(attempt);attempt.resultReportingVersion=1;for(const q of questions.filter(q=>q.section===3))attempt.listening[q.id].audioFile=audioManifest[q.id]||null;if(persist()){renderQuestion();const firstQuestionCard=app.firstElementChild;requestAnimationFrame(()=>requestAnimationFrame(()=>{if(attempt&&!attempt.submittedAt&&attempt.index===0&&app.firstElementChild===firstQuestionCard)window.scrollTo({top:0,left:0,behavior:'instant'});}));}else attempt=null;};card.append(form);app.append(card);resetStartScrollAfterPaint(card);}
// Wait for the Start DOM layout and dialog focus restoration before resetting scroll.
function resetStartScrollAfterPaint(card){
  const reset=()=>{
    if(!card.isConnected||!app.contains(card))return;
    window.scrollTo({top:0,left:0,behavior:'instant'});
    if(document.scrollingElement){document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0;}
    for(let container=app;container;container=container.parentElement){
      const style=getComputedStyle(container);
      if(/auto|scroll|overlay/.test(style.overflowY+' '+style.overflowX)){container.scrollTop=0;container.scrollLeft=0;}
    }
  };
  requestAnimationFrame(()=>requestAnimationFrame(()=>{reset();requestAnimationFrame(reset);}));
}
function renderMaterial(q,card){if(!q.material)return;const parsed=/^Q(?:4[5-9]|50)$/.test(q.id)?splitMaterialTable(q.material):null;const isTable=/[┌┬┼│]/u.test(q.material);const material=el('div',parsed?undefined:q.material,`material${!parsed&&isTable?' table-text':''}`);material.lang='ja';material.setAttribute('aria-label','Reading material');if(parsed){material.classList.add('html-material');material.append(el('div',parsed.before,'material-prose'));const frame=el('div',undefined,'table-scroll');frame.tabIndex=0;frame.setAttribute('role','region');frame.setAttribute('aria-label','Reading material table; scroll horizontally');const table=el('table'),head=el('thead'),headerRow=el('tr'),body=el('tbody');table.dataset.questionId=q.id;const columns=el('colgroup');for(const width of readingTableWidths[q.id]||parsed.headers.map(()=>100/parsed.headers.length)){const col=el('col');col.style.width=width+'%';columns.append(col);}table.append(columns);for(const text of parsed.headers){const cell=el('th',text);cell.scope='col';headerRow.append(cell);}head.append(headerRow);for(const row of parsed.rows){const tr=el('tr');for(const text of row)tr.append(el('td',text));body.append(tr);}table.append(head,body);frame.append(table);material.append(frame,el('div',parsed.after,'material-prose'));}else if(isTable){material.tabIndex=0;material.title='Scroll horizontally to read the complete table.';}card.append(material);}
function renderQuestionText(q,card){if(q.instruction)card.append(el('p',q.instruction,'instruction'));const word=readingWords[q.id];if(word)card.append(el('p',readingInstruction,'instruction'));const heading=el('h1',undefined,'question');if(word&&q.question.includes(word)){const index=q.question.indexOf(word);heading.append(document.createTextNode(q.question.slice(0,index)),el('span',word,'reading-word'),document.createTextNode(q.question.slice(index+word.length)));}else heading.textContent=q.question;card.append(heading);}
function renderQuestion(){stopAudio();if(attempt.submittedAt){showResult();return;}if(!tick())return;meta.hidden=false;const q=questions[attempt.index],sectionQs=questions.filter(x=>x.section===q.section),position=sectionQs.findIndex(x=>x.id===q.id);renderParts();document.querySelector('#section-name').textContent=`Part ${q.section}: ${PART_NAMES[q.section-1]}`;document.querySelector('#question-number').textContent=`Part question ${position+1} / ${sectionQs.length} · Overall question ${attempt.index+1} / 50`;app.replaceChildren();const card=el('section',undefined,'card question-card'),status=el('div',undefined,'question-status');const questionLabel=el('span',q.id);questionLabel.append(el('small',` · ${position+1} / ${sectionQs.length} in this section`,'question-position'));status.append(questionLabel,el('span',`${sectionQs.filter(x=>attempt.answers.some(a=>a.questionId===x.id)).length} answered`));const progress=el('div',undefined,'section-progress'),fill=el('div');fill.style.width=`${(position+1)/sectionQs.length*100}%`;progress.append(fill);card.append(status,progress);renderQuestionText(q,card);renderMaterial(q,card);
  if(q.section===3){const box=el('div',undefined,'audio'),state=attempt.listening[q.id],message=el('div',undefined,'audio-status');message.setAttribute('role','status');box.append(el('p',state.audioFile?'Listen to the audio and choose your answer.':'[Audio will be added later]'));const play=button('Play Audio',()=>playAudio(q,play,message));play.disabled=state.playCount>=state.maxPlays;box.append(play,el('p',`Plays: ${state.playCount} / ${state.maxPlays}`,'muted'),message);card.append(box);}
  const choices=el('div',undefined,'choices');choices.setAttribute('role','radiogroup');choices.setAttribute('aria-label','Answer choices');const selected=attempt.answers.find(a=>a.questionId===q.id)?.selectedChoiceId;attempt.choiceOrders[q.id].forEach((id,i)=>{const c=q.choices.find(c=>c.id===id),b=button('',()=>selectAnswer(q.id,id));b.className='choice';b.setAttribute('role','radio');b.setAttribute('aria-checked',String(selected===id));const choiceText=el('span',undefined,'choice-text');for(const run of choiceTextRuns(c.text))choiceText.append(run.parenthetical?el('span',run.text,'choice-parenthetical'):document.createTextNode(run.text));b.append(el('span','ABCD'[i],'letter'),choiceText);b.onkeydown=e=>{if(['ArrowDown','ArrowRight','ArrowUp','ArrowLeft'].includes(e.key)){e.preventDefault();const delta=['ArrowDown','ArrowRight'].includes(e.key)?1:-1;choices.children[(i+delta+4)%4].focus();}};choices.append(b);});card.append(choices);
  const actions=el('div',undefined,'actions');if(q.section!==3){const prev=button('Previous',()=>move(-1),'secondary previous');prev.disabled=position===0;actions.append(prev);}const last=position===sectionQs.length-1;const next=button(last?(q.section===4?'Submit Test':'Continue to Next Section'):'Next',()=>{if(last)finishSection();else move(1);});if(q.section===3&&!selected)next.disabled=true;actions.append(next);card.append(actions);if(q.section===3)card.append(el('p','Choose an answer to continue. You cannot return to a previous listening question.','muted'));app.append(card);}
function selectAnswer(questionId,selectedChoiceId){if(!tick())return;const old=attempt.answers.find(a=>a.questionId===questionId);if(old)old.selectedChoiceId=selectedChoiceId;else attempt.answers.push({questionId,selectedChoiceId});persist();const order=attempt.choiceOrders[questionId];app.querySelectorAll('.choice').forEach((b,i)=>b.setAttribute('aria-checked',String(order[i]===selectedChoiceId)));const sectionQs=questions.filter(q=>q.section===attempt.section);app.querySelector('.question-status span:last-child').textContent=`${sectionQs.filter(q=>attempt.answers.some(a=>a.questionId===q.id)).length} answered`;app.querySelector('.actions button:last-child').disabled=false;app.querySelectorAll('.choice')[order.indexOf(selectedChoiceId)]?.focus();}
function move(delta){if(!tick())return;const q=questions[attempt.index],target=questions[attempt.index+delta];if(!target||target.section!==attempt.section||(q.section===3&&(delta!==1||!attempt.answers.some(a=>a.questionId===q.id))))return;attempt.index+=delta;persist();renderQuestion();window.scrollTo(0,0);}
function finishSection(){const qs=questions.filter(q=>q.section===attempt.section),unanswered=qs.filter(q=>!attempt.answers.some(a=>a.questionId===q.id)).length;showConfirm(attempt.section===4?'Submit test?':`Finish Section ${attempt.section}?`,`You cannot return to this section after continuing.${unanswered?` ${unanswered} unanswered question(s) will be scored as incorrect.`:''}`,()=>{if(attempt.section===4)submit(false);else{attempt.section++;attempt.index=questions.findIndex(q=>q.section===attempt.section);persist();renderQuestion();window.scrollTo(0,0);}},attempt.section===4?'Submit Test':'Continue');}
async function playAudio(q,play,message){if(!tick())return;const state=attempt.listening[q.id];if(!state.audioFile){message.textContent='Audio is not available in this development version.';return;}if(state.playCount>=state.maxPlays||audioPlayer.status!=='idle')return;const box=play.closest('.audio');await audioPlayer.play(state.audioFile,{
onState(status){box.dataset.audioState=status;play.disabled=status!=='idle'||state.playCount>=state.maxPlays;if(status==='preparing')message.textContent='Preparing audio…';else if(status==='playing')message.textContent='Playing audio…';},
onStarted(duration){state.playCount++;persist();box.dataset.audioDuration=String(duration);box.querySelector('.muted').textContent='Plays: '+state.playCount+' / '+state.maxPlays;},
onEnded(){message.textContent='Audio finished. Plays: '+state.playCount+' / '+state.maxPlays;},
onError(error){console.error('Audio preparation failed:',error);message.textContent='Audio could not be prepared. Check your connection and tap Play Audio again. No play was counted.';}
});}
function tick(){if(!attempt||attempt.submittedAt)return true;attempt.lastSeenAt=Math.max(attempt.lastSeenAt,Date.now());const ms=remaining(attempt);const seconds=Math.ceil(ms/1000),timer=document.querySelector('#timer');timer.textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;timer.classList.toggle('warning',ms<=300000);persist();if(ms===0){submit(true);return false;}return true;}
function submit(expired){stopAudio();if(attempt.submittedAt)return;attempt.submittedAt=expired?attempt.startedAt+TEST.durationMs:Math.max(Date.now(),attempt.lastSeenAt);attempt.autoSubmitted=expired;persist();try{const id=prepareResultDelivery(grade(questions,attempt));resultDelivery.send(id,true).catch(error=>console.error('[JFT result delivery] submit send failed',error));}catch(error){console.error('[JFT result delivery] submit preparation failed',error);}if(dialog.open)dialog.close();showResult();}
function showResult(){stopAudio();meta.hidden=true;renderParts();app.replaceChildren();const r=grade(questions,attempt),card=el('section',undefined,'card');card.append(el('div','TEST COMPLETE','eyebrow'),el('h1','Your results'));if(attempt.autoSubmitted)card.append(el('p','Time is up. Your test was submitted automatically.','notice'));const details=el('div',undefined,'results-student');for(const [label,value]of STUDENT_FIELDS.map(f=>[f.label,attempt.student[f.key]||''])){const d=el('div');d.append(el('span',label),el('strong',value));details.append(d);}card.append(details,el('p','Test started: '+resultDate(attempt),'result-date'));const scores=el('div',undefined,'scores');for(const [label,value]of [['Correct Answers',`${r.correct} / 50`],['Mock Score',`${r.score} / 250`]]){const d=el('div',undefined,'score');d.append(el('span',label),el('strong',value));scores.append(d);}card.append(scores,el('p','Mock score is not an official JFT-Basic scaled score.','muted score-disclaimer'),el('h2','Section results'));for(const s of r.sections){const row=el('div',undefined,'section-result'),label=el('div',undefined,'row'),bar=el('div',undefined,'bar'),fill=el('div');label.append(el('span',`Part ${s.section} · ${PART_NAMES[s.section-1]}`),el('strong',`${s.percent}%`));fill.style.width=`${s.percent}%`;bar.append(fill);row.append(label,bar);card.append(row);}const elapsed=Math.floor(r.elapsedMs/1000);card.append(el('p',`Time taken: ${Math.floor(elapsed/60)} min ${String(elapsed%60).padStart(2,'0')} sec`));const actions=el('div',undefined,'actions');actions.append(button('Download Result',()=>downloadResult(r,card)));actions.append(button('Start a New Attempt',()=>showConfirm('Start a new attempt?','This will delete the current result and saved answers from this browser.',()=>{try{localStorage.removeItem(storageKey);attempt=null;showStart();}catch{app.prepend(el('p','Saved data could not be removed.','error'));}},'Start New Attempt'),'secondary'));card.append(actions);app.append(card);window.scrollTo({top:0,left:0,behavior:'instant'});bindResultSaving(card,r);}
function prepareResultDelivery(result){
  ensureAttemptId(attempt);attempt.resultReportingVersion=1;persist();
  resultDelivery.queue(resultPayload(questions,attempt,result,RESULT_DELIVERY),attempt);
  return attempt.attemptId;
}
function bindResultSaving(card,result){
  resultSaveUnsubscribe?.();resultSaveUnsubscribe=null;
  if(!attempt?.submittedAt)return;
  const id=ensureAttemptId(attempt),status=el('p',undefined,'muted');status.setAttribute('role','status');
  const update=()=>{if(!card.isConnected)return;const record=resultDelivery.get(id);status.textContent=record?.storageError?'Result is shown, but local saving failed. Retry saving or download the PDF.':!resultDelivery.configured?'Your result is kept on this device. Teacher saving is not configured.':record?.status==='sent'?'Result saved for your teacher.':record?.status==='sending'?'Saving result…':'Your result is kept on this device. Please retry saving.';retry.hidden=record?.status!=='pending'&&!record?.storageError;};
  const startSending=()=>{try{prepareResultDelivery(result);update();resultDelivery.send(id,true).catch(error=>{console.error('[JFT result delivery] unexpected send failure',error);status.textContent='Saving failed. Your result is still shown. Please retry saving.';retry.hidden=false;});}catch(error){console.error('[JFT result delivery] completion save failed',error);status.textContent='Local result saving failed. Retry saving or download the PDF.';retry.hidden=false;}};
  const retry=button('Retry saving',startSending,'secondary');retry.hidden=true;card.append(status,retry);
  resultSaveUnsubscribe=resultDelivery.subscribe(update);startSending();
}
async function downloadResult(result,card){const downloadButton=card.querySelector('.actions button');downloadButton.disabled=true;downloadButton.textContent='Preparing PDF…';try{const pdf=await createResultPdf(attempt,result);const blob=new Blob([pdf],{type:'application/octet-stream'});if(resultPdfUrl)URL.revokeObjectURL(resultPdfUrl);resultPdfUrl=URL.createObjectURL(blob);card.querySelector('.pdf-save')?.remove();const link=el('a','Save PDF','pdf-save');link.href=resultPdfUrl;link.download='JFT-Basic-Mock-Test-01-result.pdf';card.append(link,el('p','If the download does not start, tap Save PDF.','muted'));link.click();}catch{card.append(el('p','The PDF could not be created. Please try again.','error'));}finally{downloadButton.disabled=false;downloadButton.textContent='Download Result';}}
async function init(){try{const response=await fetch(TEST.dataUrl);if(!response.ok)throw new Error('Question data could not be loaded.');questions=await response.json();const errors=validateQuestions(questions);if(errors.length)throw new Error(errors.join('\n'));const audioResponse=await fetch(TEST.audioManifestUrl);if(!audioResponse.ok)throw new Error('Audio configuration could not be loaded.');audioManifest=await audioResponse.json();localStorage.setItem(`${storageKey}:check`,'1');localStorage.removeItem(`${storageKey}:check`);const raw=localStorage.getItem(storageKey);if(raw){attempt=JSON.parse(raw);const completed=resultDelivery.completedAttempt(attempt.attemptId);if(completed)attempt=completed;if(!validAttempt(attempt,questions))throw new Error('Saved progress is invalid. Do not continue with this saved attempt.');if(!attempt.submittedAt){ensureAttemptId(attempt);attempt.resultReportingVersion=1;persist();}for(const q of questions.filter(q=>q.section===3))attempt.listening[q.id].audioFile=audioManifest[q.id]||null;if(attempt.submittedAt)showResult();else renderQuestion();}else showStart();setInterval(()=>{if(attempt&&!attempt.submittedAt)tick();},1000);}catch(e){app.replaceChildren(el('section',undefined,'card'));app.firstChild.append(el('h1','Unable to load the test'),el('p',e.message,'error'),el('p','Open the app using Start-Test.cmd. Browser storage must be enabled.'));}}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&attempt&&!attempt.submittedAt)tick();if(!document.hidden&&attempt?.submittedAt)resultDelivery.send(attempt.attemptId,true).catch(error=>console.error('[JFT result delivery] resume send failed',error));});
window.addEventListener('storage',e=>{if(e.key===storageKey){stopAudio();attempt=null;if(dialog.open)dialog.close();meta.hidden=true;app.replaceChildren(el('h1','Test opened in another tab'),el('p','Continue in one tab to keep your progress consistent.'),button('Resume in This Tab',()=>location.reload()));}});
const textSizeKey='jft-basic:text-size:v1';
const textSizeSelect=document.querySelector('#text-size');
function setTextSize(value){const size=['standard','large','extra-large'].includes(value)?value:'large';document.documentElement.dataset.textSize=size;textSizeSelect.value=size;}
try{setTextSize(localStorage.getItem(textSizeKey));}catch{setTextSize('large');}
textSizeSelect.onchange=()=>{setTextSize(textSizeSelect.value);try{localStorage.setItem(textSizeKey,textSizeSelect.value);}catch{}};
const partsToggle=document.querySelector('#parts-toggle');
partsToggle.onclick=()=>{const open=partsToggle.getAttribute('aria-expanded')!=='true';partsToggle.setAttribute('aria-expanded',String(open));document.querySelector('#parts-panel').classList.toggle('parts-open',open);};
window.addEventListener('online',()=>resultDelivery.flush(true).catch(()=>{}));
setInterval(()=>resultDelivery.flush().catch(()=>{}),60000);
resultDelivery.flush().catch(()=>{});
// Reload only when entering/leaving the explicit teacher entry so the mode cannot linger.
window.addEventListener('hashchange',()=>{if(teacherE2EMode||location.hash==='#teacher-e2e-9-75b3cc6d0ea24a30')location.reload();});
init().then(async()=>{if(!teacherE2EMode)return;const {setupTeacherE2E}=await import('./teacher-e2e.js?e2e-v=9');setupTeacherE2E({app,storage:localStorage,storageKey,getAttempt:()=>attempt,getResult:()=>grade(questions,attempt),getRecord:id=>resultDelivery.get(id),subscribe:fn=>resultDelivery.subscribe(fn),confirmFinish:showConfirm,finish:()=>submit(false),retrySameAttempt:()=>resultDelivery.send(attempt.attemptId,true)});}).catch(error=>console.error('[JFT teacher E2E]',error));
